-- DEPRECATED: WooCommerce Import Staging Tables
-- @since 1.0.0
-- @deprecated 1.2.0 All staging is now handled by ksf_FA_ImportStagingProcessing.
-- No proprietary staging tables are created or used by this module.
